import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";

type CalEvent = {
  id: string;
  date: string;
  time: string;
  country: string;
  title: string;
  importance: string; // "3"=★★★, "2"=★★, "1"=★, "0"=연준 인사 발언(별 없음)
  source: string;
  sourceUrl: string;
};

// 오선의 미국 증시 라이브 + SAVE 앱 스타일
// 한국시간(KST) 기준 | 미국 ET→KST = +14h (서머타임 +13h, 3/8 이후)
// ★★★(3): FOMC, NFP, CPI, PCE, GDP, ISM, 소비자신뢰, 기존주택판매, 실업률
// ★★(2): ADP, PPI, 소매판매, 내구재, 국채경매, 무역수지, 미시간심리, FOMC의사록
// ★(1): JOLTS, 주택착공, NFIB, 연준지역지수, 시카고PMI, 도매재고, 실업수당
// 0: 연준 인사 발언 (별 없음)
const EVENTS: CalEvent[] = [
  // ═══════════════════ US 2026년 1월 ═══════════════════
  { id: "us-0102a", date: "2026-01-02", time: "00:00 (KST)", country: "US", title: "ISM 제조업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0103a", date: "2026-01-03", time: "00:00 (KST)", country: "US", title: "JOLTS 구인건수", importance: "1", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0105a", date: "2026-01-05", time: "22:30 (KST)", country: "US", title: "ISM 서비스업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0106a", date: "2026-01-06", time: "03:00 (KST)", country: "US", title: "3년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0107a", date: "2026-01-07", time: "22:15 (KST)", country: "US", title: "ADP 민간고용 변동", importance: "2", source: "ADP", sourceUrl: "https://adpemploymentreport.com" },
  { id: "us-0107b", date: "2026-01-07", time: "03:00 (KST)", country: "US", title: "10년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0108a", date: "2026-01-08", time: "22:30 (KST)", country: "US", title: "신규 실업수당 청구건수", importance: "1", source: "DOL", sourceUrl: "https://www.dol.gov" },
  { id: "us-0108b", date: "2026-01-08", time: "03:00 (KST)", country: "US", title: "30년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0109a", date: "2026-01-09", time: "22:30 (KST)", country: "US", title: "비농업 부문 고용 (NFP)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0109b", date: "2026-01-09", time: "22:30 (KST)", country: "US", title: "실업률", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0109c", date: "2026-01-09", time: "22:30 (KST)", country: "US", title: "평균 시간당 임금 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0110a", date: "2026-01-10", time: "00:00 (KST)", country: "US", title: "미시간 소비자심리지수 (예비)", importance: "2", source: "미시간대", sourceUrl: "https://data.sca.isr.umich.edu" },
  { id: "us-0113a", date: "2026-01-13", time: "00:00 (KST)", country: "US", title: "NFIB 중소기업 경기낙관지수", importance: "1", source: "NFIB", sourceUrl: "https://www.nfib.com" },
  { id: "us-0114a", date: "2026-01-14", time: "22:30 (KST)", country: "US", title: "PPI 생산자물가지수 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0114b", date: "2026-01-14", time: "22:30 (KST)", country: "US", title: "근원 PPI (Core PPI, 전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0115a", date: "2026-01-15", time: "22:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전년 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0115b", date: "2026-01-15", time: "22:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0115c", date: "2026-01-15", time: "22:30 (KST)", country: "US", title: "근원 CPI (Core CPI, 전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0116a", date: "2026-01-16", time: "22:30 (KST)", country: "US", title: "소매판매 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov/retail" },
  { id: "us-0116b", date: "2026-01-16", time: "22:30 (KST)", country: "US", title: "필라델피아 연준 제조업 지수", importance: "1", source: "Philadelphia Fed", sourceUrl: "https://www.philadelphiafed.org" },
  { id: "us-0116c", date: "2026-01-16", time: "22:30 (KST)", country: "US", title: "수출입 물가지수", importance: "1", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0117a", date: "2026-01-17", time: "23:15 (KST)", country: "US", title: "산업생산 & 설비가동률", importance: "1", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0121a", date: "2026-01-21", time: "22:30 (KST)", country: "US", title: "주택착공건수 & 건축허가", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0122a", date: "2026-01-22", time: "00:00 (KST)", country: "US", title: "기존주택판매", importance: "3", source: "NAR", sourceUrl: "https://www.nar.realtor" },
  { id: "us-0123a", date: "2026-01-23", time: "22:30 (KST)", country: "US", title: "신규 실업수당 청구건수", importance: "1", source: "DOL", sourceUrl: "https://www.dol.gov" },
  { id: "us-0124a", date: "2026-01-24", time: "00:00 (KST)", country: "US", title: "미시간 소비자심리지수 (최종)", importance: "2", source: "미시간대", sourceUrl: "https://data.sca.isr.umich.edu" },
  { id: "us-0127a", date: "2026-01-27", time: "00:00 (KST)", country: "US", title: "신규주택판매", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0127b", date: "2026-01-27", time: "00:00 (KST)", country: "US", title: "리치몬드 연준 제조업 지수", importance: "1", source: "Richmond Fed", sourceUrl: "https://www.richmondfed.org" },
  { id: "us-0127c", date: "2026-01-27", time: "03:00 (KST)", country: "US", title: "2년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0128a", date: "2026-01-28", time: "22:30 (KST)", country: "US", title: "내구재 주문 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0128b", date: "2026-01-28", time: "00:00 (KST)", country: "US", title: "CB 소비자신뢰지수", importance: "3", source: "Conference Board", sourceUrl: "https://www.conference-board.org" },
  { id: "us-0128c", date: "2026-01-28", time: "04:00 (KST)", country: "US", title: "FOMC 금리 결정", importance: "3", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0128d", date: "2026-01-28", time: "04:30 (KST)", country: "US", title: "연준 의장 기자회견", importance: "3", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0128e", date: "2026-01-28", time: "03:00 (KST)", country: "US", title: "5년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0129a", date: "2026-01-29", time: "03:00 (KST)", country: "US", title: "7년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0130a", date: "2026-01-30", time: "22:30 (KST)", country: "US", title: "GDP 속보치 (Q4 2025, 전분기 대비 연율)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0130b", date: "2026-01-30", time: "22:30 (KST)", country: "US", title: "PCE 물가지수 (전월 대비)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0130c", date: "2026-01-30", time: "22:30 (KST)", country: "US", title: "근원 PCE 물가지수 (Core PCE)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0130d", date: "2026-01-30", time: "22:30 (KST)", country: "US", title: "개인소득 & 소비지출", importance: "1", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0131a", date: "2026-01-31", time: "23:45 (KST)", country: "US", title: "시카고 PMI", importance: "1", source: "ISM-Chicago", sourceUrl: "https://www.ismworld.org" },

  // ═══════════════════ US 2026년 2월 ═══════════════════
  { id: "us-0203a", date: "2026-02-03", time: "00:00 (KST)", country: "US", title: "ISM 제조업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0204a", date: "2026-02-04", time: "00:00 (KST)", country: "US", title: "JOLTS 구인건수", importance: "1", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0205a", date: "2026-02-05", time: "22:15 (KST)", country: "US", title: "ADP 민간고용 변동", importance: "2", source: "ADP", sourceUrl: "https://adpemploymentreport.com" },
  { id: "us-0205b", date: "2026-02-05", time: "00:00 (KST)", country: "US", title: "ISM 서비스업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0205c", date: "2026-02-05", time: "22:30 (KST)", country: "US", title: "무역수지", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0206a", date: "2026-02-06", time: "22:30 (KST)", country: "US", title: "비농업생산성 최종 (Q4, 전분기 대비)", importance: "1", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0206b", date: "2026-02-06", time: "22:30 (KST)", country: "US", title: "단위노동비용 (전분기 대비 최종)", importance: "1", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0206c", date: "2026-02-06", time: "22:30 (KST)", country: "US", title: "비농업 부문 고용 (NFP)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0206d", date: "2026-02-06", time: "22:30 (KST)", country: "US", title: "실업률", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0206e", date: "2026-02-06", time: "22:30 (KST)", country: "US", title: "평균 시간당 임금 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0210a", date: "2026-02-10", time: "00:00 (KST)", country: "US", title: "NFIB 중소기업 경기낙관지수", importance: "1", source: "NFIB", sourceUrl: "https://www.nfib.com" },
  { id: "us-0210b", date: "2026-02-10", time: "03:00 (KST)", country: "US", title: "3년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0211a", date: "2026-02-11", time: "22:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전년 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0211b", date: "2026-02-11", time: "22:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0211c", date: "2026-02-11", time: "22:30 (KST)", country: "US", title: "근원 CPI (Core CPI, 전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0211d", date: "2026-02-11", time: "03:00 (KST)", country: "US", title: "10년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0212a", date: "2026-02-12", time: "03:00 (KST)", country: "US", title: "30년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0213a", date: "2026-02-13", time: "22:30 (KST)", country: "US", title: "PPI 생산자물가지수 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0214a", date: "2026-02-14", time: "22:30 (KST)", country: "US", title: "소매판매 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov/retail" },
  { id: "us-0214b", date: "2026-02-14", time: "22:30 (KST)", country: "US", title: "수출입 물가지수", importance: "1", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0218a", date: "2026-02-18", time: "22:30 (KST)", country: "US", title: "NY 연준 제조업 지수 (Empire State)", importance: "1", source: "NY Fed", sourceUrl: "https://www.newyorkfed.org" },
  { id: "us-0218b", date: "2026-02-18", time: "06:00 (KST)", country: "US", title: "장기자본흐름 (TIC)", importance: "1", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0219a", date: "2026-02-19", time: "22:30 (KST)", country: "US", title: "주택착공건수 & 건축허가", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0219b", date: "2026-02-19", time: "23:15 (KST)", country: "US", title: "산업생산 & 설비가동률", importance: "1", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0219c", date: "2026-02-19", time: "04:00 (KST)", country: "US", title: "FOMC 의사록 공개 (1월 회의)", importance: "2", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0220a", date: "2026-02-20", time: "22:30 (KST)", country: "US", title: "필라델피아 연준 제조업 지수", importance: "1", source: "Philadelphia Fed", sourceUrl: "https://www.philadelphiafed.org" },
  { id: "us-0220b", date: "2026-02-20", time: "00:00 (KST)", country: "US", title: "기존주택판매", importance: "3", source: "NAR", sourceUrl: "https://www.nar.realtor" },
  { id: "us-0220c", date: "2026-02-20", time: "00:00 (KST)", country: "US", title: "경기선행지수 (LEI)", importance: "1", source: "Conference Board", sourceUrl: "https://www.conference-board.org" },
  { id: "us-0224a", date: "2026-02-24", time: "00:30 (KST)", country: "US", title: "달라스 연준 제조업 지수", importance: "1", source: "Dallas Fed", sourceUrl: "https://www.dallasfed.org" },
  { id: "us-0224b", date: "2026-02-24", time: "03:00 (KST)", country: "US", title: "2년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0225a", date: "2026-02-25", time: "00:00 (KST)", country: "US", title: "리치몬드 연준 제조업 지수", importance: "1", source: "Richmond Fed", sourceUrl: "https://www.richmondfed.org" },
  { id: "us-0225b", date: "2026-02-25", time: "23:00 (KST)", country: "US", title: "S&P/케이스-실러 주택가격지수", importance: "1", source: "S&P", sourceUrl: "https://www.spglobal.com" },
  { id: "us-0225c", date: "2026-02-25", time: "00:00 (KST)", country: "US", title: "CB 소비자신뢰지수", importance: "3", source: "Conference Board", sourceUrl: "https://www.conference-board.org" },
  { id: "us-0225d", date: "2026-02-25", time: "00:00 (KST)", country: "US", title: "신규주택판매", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0225e", date: "2026-02-25", time: "00:00 (KST)", country: "US", title: "도매재고 (전월 대비)", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0225f", date: "2026-02-25", time: "03:00 (KST)", country: "US", title: "5년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0226a", date: "2026-02-26", time: "22:30 (KST)", country: "US", title: "내구재 주문 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0226b", date: "2026-02-26", time: "03:00 (KST)", country: "US", title: "7년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0227a", date: "2026-02-27", time: "22:30 (KST)", country: "US", title: "GDP 수정치 (Q4 2025, 전분기 대비 연율)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0227b", date: "2026-02-27", time: "00:00 (KST)", country: "US", title: "잠정주택판매지수", importance: "1", source: "NAR", sourceUrl: "https://www.nar.realtor" },
  { id: "us-0228a", date: "2026-02-28", time: "22:30 (KST)", country: "US", title: "PCE 물가지수 (전월 대비)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0228b", date: "2026-02-28", time: "22:30 (KST)", country: "US", title: "근원 PCE 물가지수 (Core PCE)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0228c", date: "2026-02-28", time: "22:30 (KST)", country: "US", title: "개인소득 & 소비지출", importance: "1", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0228d", date: "2026-02-28", time: "23:45 (KST)", country: "US", title: "시카고 PMI", importance: "1", source: "ISM-Chicago", sourceUrl: "https://www.ismworld.org" },

  // ═══════════════════ US 2026년 3월 ═══════════════════
  { id: "us-0303a", date: "2026-03-03", time: "00:00 (KST)", country: "US", title: "ISM 제조업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0304a", date: "2026-03-04", time: "22:15 (KST)", country: "US", title: "ADP 민간고용 변동", importance: "2", source: "ADP", sourceUrl: "https://adpemploymentreport.com" },
  { id: "us-0304b", date: "2026-03-04", time: "00:00 (KST)", country: "US", title: "JOLTS 구인건수", importance: "1", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0304c", date: "2026-03-04", time: "00:00 (KST)", country: "US", title: "ISM 서비스업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0305a", date: "2026-03-05", time: "22:30 (KST)", country: "US", title: "신규 실업수당 청구건수", importance: "1", source: "DOL", sourceUrl: "https://www.dol.gov" },
  { id: "us-0305b", date: "2026-03-05", time: "04:00 (KST)", country: "US", title: "베이지북 발간", importance: "2", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0306a", date: "2026-03-06", time: "22:30 (KST)", country: "US", title: "비농업 부문 고용 (NFP)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0306b", date: "2026-03-06", time: "22:30 (KST)", country: "US", title: "실업률", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0306c", date: "2026-03-06", time: "22:30 (KST)", country: "US", title: "평균 시간당 임금 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0309a", date: "2026-03-09", time: "03:00 (KST)", country: "US", title: "3년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0310a", date: "2026-03-10", time: "19:00 (KST)", country: "US", title: "NFIB 중소기업 경기낙관지수", importance: "1", source: "NFIB", sourceUrl: "https://www.nfib.com" },
  { id: "us-0310b", date: "2026-03-10", time: "23:00 (KST)", country: "US", title: "기존주택판매", importance: "3", source: "NAR", sourceUrl: "https://www.nar.realtor" },
  { id: "us-0310c", date: "2026-03-10", time: "03:00 (KST)", country: "US", title: "10년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0311a", date: "2026-03-11", time: "21:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전년 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0311b", date: "2026-03-11", time: "21:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0311c", date: "2026-03-11", time: "21:30 (KST)", country: "US", title: "근원 CPI (Core CPI, 전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0311d", date: "2026-03-11", time: "03:00 (KST)", country: "US", title: "30년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0312a", date: "2026-03-12", time: "21:30 (KST)", country: "US", title: "무역수지", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0312b", date: "2026-03-12", time: "21:30 (KST)", country: "US", title: "신규 실업수당 청구건수", importance: "1", source: "DOL", sourceUrl: "https://www.dol.gov" },
  { id: "us-0312c", date: "2026-03-12", time: "21:30 (KST)", country: "US", title: "주택착공건수 & 건축허가", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0313a", date: "2026-03-13", time: "21:30 (KST)", country: "US", title: "PPI 생산자물가지수 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0313b", date: "2026-03-13", time: "21:30 (KST)", country: "US", title: "내구재 주문 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0313c", date: "2026-03-13", time: "23:00 (KST)", country: "US", title: "미시간 소비자심리지수 (예비)", importance: "2", source: "미시간대", sourceUrl: "https://data.sca.isr.umich.edu" },
  { id: "us-0316a", date: "2026-03-16", time: "21:30 (KST)", country: "US", title: "소매판매 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov/retail" },
  { id: "us-0316b", date: "2026-03-16", time: "21:30 (KST)", country: "US", title: "NY 연준 제조업 지수 (Empire State)", importance: "1", source: "NY Fed", sourceUrl: "https://www.newyorkfed.org" },
  { id: "us-0317a", date: "2026-03-17", time: "22:15 (KST)", country: "US", title: "산업생산 & 설비가동률", importance: "1", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0318a", date: "2026-03-18", time: "03:00 (KST)", country: "US", title: "FOMC 금리 결정 & 경제전망 (SEP/점도표)", importance: "3", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0318b", date: "2026-03-18", time: "03:30 (KST)", country: "US", title: "연준 의장 기자회견", importance: "3", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0319a", date: "2026-03-19", time: "21:30 (KST)", country: "US", title: "필라델피아 연준 제조업 지수", importance: "1", source: "Philadelphia Fed", sourceUrl: "https://www.philadelphiafed.org" },
  { id: "us-0319b", date: "2026-03-19", time: "21:30 (KST)", country: "US", title: "신규 실업수당 청구건수", importance: "1", source: "DOL", sourceUrl: "https://www.dol.gov" },
  { id: "us-0319c", date: "2026-03-19", time: "23:00 (KST)", country: "US", title: "기존주택판매", importance: "3", source: "NAR", sourceUrl: "https://www.nar.realtor" },
  { id: "us-0320a", date: "2026-03-20", time: "23:00 (KST)", country: "US", title: "경기선행지수 (LEI)", importance: "1", source: "Conference Board", sourceUrl: "https://www.conference-board.org" },
  { id: "us-0320b", date: "2026-03-20", time: "장중", country: "US", title: "네 마녀의 날 (Quadruple Witching)", importance: "2", source: "CME Group", sourceUrl: "https://www.cmegroup.com" },
  { id: "us-0323a", date: "2026-03-23", time: "03:00 (KST)", country: "US", title: "2년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0324a", date: "2026-03-24", time: "23:00 (KST)", country: "US", title: "리치몬드 연준 제조업 지수", importance: "1", source: "Richmond Fed", sourceUrl: "https://www.richmondfed.org" },
  { id: "us-0324b", date: "2026-03-24", time: "23:00 (KST)", country: "US", title: "신규주택판매", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0324c", date: "2026-03-24", time: "23:00 (KST)", country: "US", title: "도매재고 (전월 대비)", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0324d", date: "2026-03-24", time: "03:00 (KST)", country: "US", title: "5년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0325a", date: "2026-03-25", time: "23:00 (KST)", country: "US", title: "CB 소비자신뢰지수", importance: "3", source: "Conference Board", sourceUrl: "https://www.conference-board.org" },
  { id: "us-0325b", date: "2026-03-25", time: "21:30 (KST)", country: "US", title: "내구재 주문 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0325c", date: "2026-03-25", time: "03:00 (KST)", country: "US", title: "7년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0326a", date: "2026-03-26", time: "21:30 (KST)", country: "US", title: "GDP 최종치 (Q4 2025)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0327a", date: "2026-03-27", time: "21:30 (KST)", country: "US", title: "PCE 물가지수 (전월 대비)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0327b", date: "2026-03-27", time: "21:30 (KST)", country: "US", title: "근원 PCE 물가지수 (Core PCE)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0327c", date: "2026-03-27", time: "21:30 (KST)", country: "US", title: "개인소득 & 소비지출", importance: "1", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0327d", date: "2026-03-27", time: "23:00 (KST)", country: "US", title: "미시간 소비자심리지수 (최종)", importance: "2", source: "미시간대", sourceUrl: "https://data.sca.isr.umich.edu" },
  { id: "us-0327e", date: "2026-03-27", time: "23:00 (KST)", country: "US", title: "잠정주택판매지수", importance: "1", source: "NAR", sourceUrl: "https://www.nar.realtor" },
  { id: "us-0330a", date: "2026-03-30", time: "23:30 (KST)", country: "US", title: "달라스 연준 제조업 지수", importance: "1", source: "Dallas Fed", sourceUrl: "https://www.dallasfed.org" },
  { id: "us-0331a", date: "2026-03-31", time: "22:00 (KST)", country: "US", title: "S&P/케이스-실러 주택가격지수", importance: "1", source: "S&P", sourceUrl: "https://www.spglobal.com" },
  { id: "us-0331b", date: "2026-03-31", time: "22:45 (KST)", country: "US", title: "시카고 PMI", importance: "1", source: "ISM-Chicago", sourceUrl: "https://www.ismworld.org" },

  // ═══════════════════ US 2026년 4월 ═══════════════════
  { id: "us-0401a", date: "2026-04-01", time: "23:00 (KST)", country: "US", title: "ISM 제조업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0402a", date: "2026-04-02", time: "21:30 (KST)", country: "US", title: "ADP 민간고용 변동", importance: "2", source: "ADP", sourceUrl: "https://adpemploymentreport.com" },
  { id: "us-0402b", date: "2026-04-02", time: "23:00 (KST)", country: "US", title: "JOLTS 구인건수", importance: "1", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0403a", date: "2026-04-03", time: "23:00 (KST)", country: "US", title: "ISM 서비스업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0403b", date: "2026-04-03", time: "21:30 (KST)", country: "US", title: "비농업 부문 고용 (NFP)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0403c", date: "2026-04-03", time: "21:30 (KST)", country: "US", title: "실업률", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0403d", date: "2026-04-03", time: "21:30 (KST)", country: "US", title: "평균 시간당 임금 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0403e", date: "2026-04-03", time: "21:30 (KST)", country: "US", title: "무역수지", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0407a", date: "2026-04-07", time: "02:00 (KST)", country: "US", title: "3년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0408a", date: "2026-04-08", time: "03:00 (KST)", country: "US", title: "FOMC 의사록 공개 (3월 회의)", importance: "2", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0408b", date: "2026-04-08", time: "02:00 (KST)", country: "US", title: "10년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0409a", date: "2026-04-09", time: "02:00 (KST)", country: "US", title: "30년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0410a", date: "2026-04-10", time: "21:30 (KST)", country: "US", title: "NFIB 중소기업 경기낙관지수", importance: "1", source: "NFIB", sourceUrl: "https://www.nfib.com" },
  { id: "us-0414a", date: "2026-04-14", time: "21:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전년 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0414b", date: "2026-04-14", time: "21:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0414c", date: "2026-04-14", time: "21:30 (KST)", country: "US", title: "근원 CPI (Core CPI, 전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0415a", date: "2026-04-15", time: "21:30 (KST)", country: "US", title: "PPI 생산자물가지수 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0415b", date: "2026-04-15", time: "21:30 (KST)", country: "US", title: "소매판매 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov/retail" },
  { id: "us-0416a", date: "2026-04-16", time: "21:30 (KST)", country: "US", title: "주택착공건수 & 건축허가", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0416b", date: "2026-04-16", time: "21:30 (KST)", country: "US", title: "필라델피아 연준 제조업 지수", importance: "1", source: "Philadelphia Fed", sourceUrl: "https://www.philadelphiafed.org" },
  { id: "us-0417a", date: "2026-04-17", time: "22:15 (KST)", country: "US", title: "산업생산 & 설비가동률", importance: "1", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0417b", date: "2026-04-17", time: "23:00 (KST)", country: "US", title: "미시간 소비자심리지수 (예비)", importance: "2", source: "미시간대", sourceUrl: "https://data.sca.isr.umich.edu" },
  { id: "us-0421a", date: "2026-04-21", time: "02:00 (KST)", country: "US", title: "2년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0422a", date: "2026-04-22", time: "23:00 (KST)", country: "US", title: "기존주택판매", importance: "3", source: "NAR", sourceUrl: "https://www.nar.realtor" },
  { id: "us-0422b", date: "2026-04-22", time: "23:00 (KST)", country: "US", title: "리치몬드 연준 제조업 지수", importance: "1", source: "Richmond Fed", sourceUrl: "https://www.richmondfed.org" },
  { id: "us-0422c", date: "2026-04-22", time: "02:00 (KST)", country: "US", title: "5년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0423a", date: "2026-04-23", time: "23:00 (KST)", country: "US", title: "신규주택판매", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0423b", date: "2026-04-23", time: "02:00 (KST)", country: "US", title: "7년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0424a", date: "2026-04-24", time: "21:30 (KST)", country: "US", title: "내구재 주문 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0428a", date: "2026-04-28", time: "23:00 (KST)", country: "US", title: "CB 소비자신뢰지수", importance: "3", source: "Conference Board", sourceUrl: "https://www.conference-board.org" },
  { id: "us-0429a", date: "2026-04-29", time: "03:00 (KST)", country: "US", title: "FOMC 금리 결정", importance: "3", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0429b", date: "2026-04-29", time: "03:30 (KST)", country: "US", title: "연준 의장 기자회견", importance: "3", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0430a", date: "2026-04-30", time: "21:30 (KST)", country: "US", title: "GDP 속보치 (Q1 2026, 전분기 대비 연율)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0430b", date: "2026-04-30", time: "21:30 (KST)", country: "US", title: "PCE 물가지수 (전월 대비)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0430c", date: "2026-04-30", time: "21:30 (KST)", country: "US", title: "근원 PCE 물가지수 (Core PCE)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0430d", date: "2026-04-30", time: "22:45 (KST)", country: "US", title: "시카고 PMI", importance: "1", source: "ISM-Chicago", sourceUrl: "https://www.ismworld.org" },

  // ═══════════════════ US 2026년 5월 ═══════════════════
  { id: "us-0501a", date: "2026-05-01", time: "23:00 (KST)", country: "US", title: "ISM 제조업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0505a", date: "2026-05-05", time: "23:00 (KST)", country: "US", title: "ISM 서비스업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0505b", date: "2026-05-05", time: "23:00 (KST)", country: "US", title: "JOLTS 구인건수", importance: "1", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0506a", date: "2026-05-06", time: "21:15 (KST)", country: "US", title: "ADP 민간고용 변동", importance: "2", source: "ADP", sourceUrl: "https://adpemploymentreport.com" },
  { id: "us-0506b", date: "2026-05-06", time: "21:30 (KST)", country: "US", title: "무역수지", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0508a", date: "2026-05-08", time: "21:30 (KST)", country: "US", title: "비농업 부문 고용 (NFP)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0508b", date: "2026-05-08", time: "21:30 (KST)", country: "US", title: "실업률", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0508c", date: "2026-05-08", time: "21:30 (KST)", country: "US", title: "평균 시간당 임금 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0511a", date: "2026-05-11", time: "02:00 (KST)", country: "US", title: "3년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0512a", date: "2026-05-12", time: "21:30 (KST)", country: "US", title: "NFIB 중소기업 경기낙관지수", importance: "1", source: "NFIB", sourceUrl: "https://www.nfib.com" },
  { id: "us-0512b", date: "2026-05-12", time: "02:00 (KST)", country: "US", title: "10년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0513a", date: "2026-05-13", time: "21:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전년 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0513b", date: "2026-05-13", time: "21:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0513c", date: "2026-05-13", time: "21:30 (KST)", country: "US", title: "근원 CPI (Core CPI, 전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0513d", date: "2026-05-13", time: "02:00 (KST)", country: "US", title: "30년물 국채 경매", importance: "2", source: "Treasury", sourceUrl: "https://home.treasury.gov" },
  { id: "us-0514a", date: "2026-05-14", time: "21:30 (KST)", country: "US", title: "PPI 생산자물가지수 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0515a", date: "2026-05-15", time: "21:30 (KST)", country: "US", title: "소매판매 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov/retail" },
  { id: "us-0515b", date: "2026-05-15", time: "21:30 (KST)", country: "US", title: "NY 연준 제조업 지수 (Empire State)", importance: "1", source: "NY Fed", sourceUrl: "https://www.newyorkfed.org" },
  { id: "us-0515c", date: "2026-05-15", time: "23:00 (KST)", country: "US", title: "미시간 소비자심리지수 (예비)", importance: "2", source: "미시간대", sourceUrl: "https://data.sca.isr.umich.edu" },
  { id: "us-0519a", date: "2026-05-19", time: "21:30 (KST)", country: "US", title: "주택착공건수 & 건축허가", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0520a", date: "2026-05-20", time: "03:00 (KST)", country: "US", title: "FOMC 의사록 공개 (4월 회의)", importance: "2", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0521a", date: "2026-05-21", time: "21:30 (KST)", country: "US", title: "필라델피아 연준 제조업 지수", importance: "1", source: "Philadelphia Fed", sourceUrl: "https://www.philadelphiafed.org" },
  { id: "us-0521b", date: "2026-05-21", time: "23:00 (KST)", country: "US", title: "기존주택판매", importance: "3", source: "NAR", sourceUrl: "https://www.nar.realtor" },
  { id: "us-0526a", date: "2026-05-26", time: "23:00 (KST)", country: "US", title: "CB 소비자신뢰지수", importance: "3", source: "Conference Board", sourceUrl: "https://www.conference-board.org" },
  { id: "us-0526b", date: "2026-05-26", time: "23:00 (KST)", country: "US", title: "리치몬드 연준 제조업 지수", importance: "1", source: "Richmond Fed", sourceUrl: "https://www.richmondfed.org" },
  { id: "us-0526c", date: "2026-05-26", time: "23:00 (KST)", country: "US", title: "신규주택판매", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0528a", date: "2026-05-28", time: "21:30 (KST)", country: "US", title: "GDP 수정치 (Q1 2026, 전분기 대비 연율)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0528b", date: "2026-05-28", time: "21:30 (KST)", country: "US", title: "내구재 주문 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0529a", date: "2026-05-29", time: "21:30 (KST)", country: "US", title: "PCE 물가지수 (전월 대비)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0529b", date: "2026-05-29", time: "21:30 (KST)", country: "US", title: "근원 PCE 물가지수 (Core PCE)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0529c", date: "2026-05-29", time: "23:00 (KST)", country: "US", title: "미시간 소비자심리지수 (최종)", importance: "2", source: "미시간대", sourceUrl: "https://data.sca.isr.umich.edu" },

  // ═══════════════════ US 2026년 6월 ═══════════════════
  { id: "us-0601a", date: "2026-06-01", time: "23:00 (KST)", country: "US", title: "ISM 제조업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0602a", date: "2026-06-02", time: "23:00 (KST)", country: "US", title: "JOLTS 구인건수", importance: "1", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0603a", date: "2026-06-03", time: "21:15 (KST)", country: "US", title: "ADP 민간고용 변동", importance: "2", source: "ADP", sourceUrl: "https://adpemploymentreport.com" },
  { id: "us-0603b", date: "2026-06-03", time: "23:00 (KST)", country: "US", title: "ISM 서비스업 PMI", importance: "3", source: "ISM", sourceUrl: "https://www.ismworld.org" },
  { id: "us-0603c", date: "2026-06-03", time: "03:00 (KST)", country: "US", title: "베이지북 발간", importance: "2", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0605a", date: "2026-06-05", time: "21:30 (KST)", country: "US", title: "비농업 부문 고용 (NFP)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0605b", date: "2026-06-05", time: "21:30 (KST)", country: "US", title: "실업률", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0605c", date: "2026-06-05", time: "21:30 (KST)", country: "US", title: "평균 시간당 임금 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0605d", date: "2026-06-05", time: "21:30 (KST)", country: "US", title: "무역수지", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0609a", date: "2026-06-09", time: "21:30 (KST)", country: "US", title: "NFIB 중소기업 경기낙관지수", importance: "1", source: "NFIB", sourceUrl: "https://www.nfib.com" },
  { id: "us-0610a", date: "2026-06-10", time: "21:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전년 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0610b", date: "2026-06-10", time: "21:30 (KST)", country: "US", title: "CPI 소비자물가지수 (전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0610c", date: "2026-06-10", time: "21:30 (KST)", country: "US", title: "근원 CPI (Core CPI, 전월 대비)", importance: "3", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0611a", date: "2026-06-11", time: "21:30 (KST)", country: "US", title: "PPI 생산자물가지수 (전월 대비)", importance: "2", source: "BLS", sourceUrl: "https://www.bls.gov" },
  { id: "us-0612a", date: "2026-06-12", time: "21:30 (KST)", country: "US", title: "미시간 소비자심리지수 (예비)", importance: "2", source: "미시간대", sourceUrl: "https://data.sca.isr.umich.edu" },
  { id: "us-0616a", date: "2026-06-16", time: "21:30 (KST)", country: "US", title: "소매판매 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov/retail" },
  { id: "us-0616b", date: "2026-06-16", time: "21:30 (KST)", country: "US", title: "NY 연준 제조업 지수 (Empire State)", importance: "1", source: "NY Fed", sourceUrl: "https://www.newyorkfed.org" },
  { id: "us-0617a", date: "2026-06-17", time: "03:00 (KST)", country: "US", title: "FOMC 금리 결정 & 경제전망 (SEP/점도표)", importance: "3", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0617b", date: "2026-06-17", time: "03:30 (KST)", country: "US", title: "연준 의장 기자회견", importance: "3", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0617c", date: "2026-06-17", time: "21:30 (KST)", country: "US", title: "주택착공건수 & 건축허가", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0618a", date: "2026-06-18", time: "21:30 (KST)", country: "US", title: "필라델피아 연준 제조업 지수", importance: "1", source: "Philadelphia Fed", sourceUrl: "https://www.philadelphiafed.org" },
  { id: "us-0618b", date: "2026-06-18", time: "22:15 (KST)", country: "US", title: "산업생산 & 설비가동률", importance: "1", source: "Federal Reserve", sourceUrl: "https://www.federalreserve.gov" },
  { id: "us-0619a", date: "2026-06-19", time: "장중", country: "US", title: "네 마녀의 날 (Quadruple Witching)", importance: "2", source: "CME Group", sourceUrl: "https://www.cmegroup.com" },
  { id: "us-0622a", date: "2026-06-22", time: "23:00 (KST)", country: "US", title: "기존주택판매", importance: "3", source: "NAR", sourceUrl: "https://www.nar.realtor" },
  { id: "us-0623a", date: "2026-06-23", time: "23:00 (KST)", country: "US", title: "리치몬드 연준 제조업 지수", importance: "1", source: "Richmond Fed", sourceUrl: "https://www.richmondfed.org" },
  { id: "us-0623b", date: "2026-06-23", time: "23:00 (KST)", country: "US", title: "신규주택판매", importance: "1", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0624a", date: "2026-06-24", time: "23:00 (KST)", country: "US", title: "CB 소비자신뢰지수", importance: "3", source: "Conference Board", sourceUrl: "https://www.conference-board.org" },
  { id: "us-0625a", date: "2026-06-25", time: "21:30 (KST)", country: "US", title: "내구재 주문 (전월 대비)", importance: "2", source: "Census Bureau", sourceUrl: "https://www.census.gov" },
  { id: "us-0625b", date: "2026-06-25", time: "21:30 (KST)", country: "US", title: "GDP 최종치 (Q1 2026)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0626a", date: "2026-06-26", time: "21:30 (KST)", country: "US", title: "PCE 물가지수 (전월 대비)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0626b", date: "2026-06-26", time: "21:30 (KST)", country: "US", title: "근원 PCE 물가지수 (Core PCE)", importance: "3", source: "BEA", sourceUrl: "https://www.bea.gov" },
  { id: "us-0626c", date: "2026-06-26", time: "23:00 (KST)", country: "US", title: "미시간 소비자심리지수 (최종)", importance: "2", source: "미시간대", sourceUrl: "https://data.sca.isr.umich.edu" },

  // ═══════════════════ KR 2026년 1월 ═══════════════════
  { id: "kr-0101a", date: "2026-01-01", time: "09:00 (KST)", country: "KR", title: "수출 전년 대비", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0101b", date: "2026-01-01", time: "09:00 (KST)", country: "KR", title: "수입 전년 대비", importance: "2", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0101c", date: "2026-01-01", time: "09:00 (KST)", country: "KR", title: "무역수지", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0107a", date: "2026-01-07", time: "08:00 (KST)", country: "KR", title: "소비자물가지수 CPI (전년 대비)", importance: "3", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0107b", date: "2026-01-07", time: "08:00 (KST)", country: "KR", title: "소비자물가지수 CPI (전월 대비)", importance: "3", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0115a", date: "2026-01-15", time: "10:00 (KST)", country: "KR", title: "한국은행 기준금리 결정", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0115b", date: "2026-01-15", time: "11:20 (KST)", country: "KR", title: "한국은행 총재 기자회견", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0117a", date: "2026-01-17", time: "06:00 (KST)", country: "KR", title: "수출입물가지수 (전년 대비)", importance: "1", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0120a", date: "2026-01-20", time: "08:00 (KST)", country: "KR", title: "생산자물가지수 PPI (전월 대비)", importance: "2", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0122a", date: "2026-01-22", time: "08:00 (KST)", country: "KR", title: "소비자동향조사 (CSI)", importance: "1", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0128a", date: "2026-01-28", time: "08:00 (KST)", country: "KR", title: "GDP 속보치 (Q4 2025, 전분기 대비)", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0130a", date: "2026-01-30", time: "08:00 (KST)", country: "KR", title: "광공업생산지수 (전월 대비)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0130b", date: "2026-01-30", time: "08:00 (KST)", country: "KR", title: "소매판매액지수 (전월 대비)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0130c", date: "2026-01-30", time: "08:00 (KST)", country: "KR", title: "서비스업생산지수 (전월 대비)", importance: "1", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0130d", date: "2026-01-30", time: "08:00 (KST)", country: "KR", title: "설비투자지수 (전월 대비)", importance: "1", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  // ═══════════════════ KR 2026년 2월 ═══════════════════
  { id: "kr-0201a", date: "2026-02-01", time: "09:00 (KST)", country: "KR", title: "수출 전년 대비", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0201b", date: "2026-02-01", time: "09:00 (KST)", country: "KR", title: "수입 전년 대비", importance: "2", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0201c", date: "2026-02-01", time: "09:00 (KST)", country: "KR", title: "무역수지", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0205a", date: "2026-02-05", time: "08:00 (KST)", country: "KR", title: "소비자물가지수 CPI (전년 대비)", importance: "3", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0205b", date: "2026-02-05", time: "08:00 (KST)", country: "KR", title: "소비자물가지수 CPI (전월 대비)", importance: "3", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0206a", date: "2026-02-06", time: "08:00 (KST)", country: "KR", title: "경상수지", importance: "2", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0206b", date: "2026-02-06", time: "06:00 (KST)", country: "KR", title: "외환보유고", importance: "1", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0211a", date: "2026-02-11", time: "08:00 (KST)", country: "KR", title: "실업률 (계절조정)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0220a", date: "2026-02-20", time: "08:00 (KST)", country: "KR", title: "생산자물가지수 PPI (전월 대비)", importance: "2", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0226a", date: "2026-02-26", time: "10:00 (KST)", country: "KR", title: "한국은행 기준금리 결정", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0226b", date: "2026-02-26", time: "11:20 (KST)", country: "KR", title: "한국은행 총재 기자회견", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0227a", date: "2026-02-27", time: "08:00 (KST)", country: "KR", title: "광공업생산지수 (전월 대비)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0227b", date: "2026-02-27", time: "08:00 (KST)", country: "KR", title: "소매판매액지수 (전월 대비)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  // ═══════════════════ KR 2026년 3월 ═══════════════════
  { id: "kr-0301a", date: "2026-03-01", time: "09:00 (KST)", country: "KR", title: "수출 전년 대비", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0301b", date: "2026-03-01", time: "09:00 (KST)", country: "KR", title: "수입 전년 대비", importance: "2", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0301c", date: "2026-03-01", time: "09:00 (KST)", country: "KR", title: "무역수지", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0304a", date: "2026-03-04", time: "08:00 (KST)", country: "KR", title: "광공업생산 (전월 대비, 계절조정)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0304b", date: "2026-03-04", time: "08:00 (KST)", country: "KR", title: "소매판매액지수 (전월 대비)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0305a", date: "2026-03-05", time: "06:00 (KST)", country: "KR", title: "외환보유고", importance: "1", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0306a", date: "2026-03-06", time: "08:00 (KST)", country: "KR", title: "소비자물가지수 CPI (전년 대비)", importance: "3", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0306b", date: "2026-03-06", time: "08:00 (KST)", country: "KR", title: "소비자물가지수 CPI (전월 대비)", importance: "3", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0306c", date: "2026-03-06", time: "08:00 (KST)", country: "KR", title: "경상수지", importance: "2", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0310a", date: "2026-03-10", time: "08:00 (KST)", country: "KR", title: "GDP (전분기 대비)", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0313a", date: "2026-03-13", time: "12:00 (KST)", country: "KR", title: "M2 통화공급", importance: "1", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0317a", date: "2026-03-17", time: "06:00 (KST)", country: "KR", title: "수출입물가지수 (전년 대비)", importance: "1", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0318a", date: "2026-03-18", time: "08:00 (KST)", country: "KR", title: "실업률 (계절조정)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0320a", date: "2026-03-20", time: "08:00 (KST)", country: "KR", title: "생산자물가지수 PPI (전월 대비)", importance: "2", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  // ═══════════════════ KR 2026년 4~6월 ═══════════════════
  { id: "kr-0401a", date: "2026-04-01", time: "09:00 (KST)", country: "KR", title: "수출 전년 대비", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0401b", date: "2026-04-01", time: "09:00 (KST)", country: "KR", title: "무역수지", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0403a", date: "2026-04-03", time: "08:00 (KST)", country: "KR", title: "광공업생산지수 (전월 대비)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0403b", date: "2026-04-03", time: "08:00 (KST)", country: "KR", title: "소매판매액지수 (전월 대비)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0407a", date: "2026-04-07", time: "08:00 (KST)", country: "KR", title: "소비자물가지수 CPI (전년 대비)", importance: "3", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0407b", date: "2026-04-07", time: "08:00 (KST)", country: "KR", title: "소비자물가지수 CPI (전월 대비)", importance: "3", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0409a", date: "2026-04-09", time: "10:00 (KST)", country: "KR", title: "한국은행 기준금리 결정", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0409b", date: "2026-04-09", time: "11:20 (KST)", country: "KR", title: "한국은행 총재 기자회견", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0416a", date: "2026-04-16", time: "08:00 (KST)", country: "KR", title: "실업률 (계절조정)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0420a", date: "2026-04-20", time: "08:00 (KST)", country: "KR", title: "생산자물가지수 PPI (전월 대비)", importance: "2", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0428a", date: "2026-04-28", time: "08:00 (KST)", country: "KR", title: "GDP 속보치 (Q1 2026, 전분기 대비)", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0501a", date: "2026-05-01", time: "09:00 (KST)", country: "KR", title: "수출 전년 대비", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0501b", date: "2026-05-01", time: "09:00 (KST)", country: "KR", title: "무역수지", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0505a", date: "2026-05-05", time: "08:00 (KST)", country: "KR", title: "소비자물가지수 CPI (전년 대비)", importance: "3", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0513a", date: "2026-05-13", time: "08:00 (KST)", country: "KR", title: "실업률 (계절조정)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0520a", date: "2026-05-20", time: "08:00 (KST)", country: "KR", title: "생산자물가지수 PPI (전월 대비)", importance: "2", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0528a", date: "2026-05-28", time: "10:00 (KST)", country: "KR", title: "한국은행 기준금리 결정", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0528b", date: "2026-05-28", time: "11:20 (KST)", country: "KR", title: "한국은행 총재 기자회견", importance: "3", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0529a", date: "2026-05-29", time: "08:00 (KST)", country: "KR", title: "광공업생산지수 (전월 대비)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0529b", date: "2026-05-29", time: "08:00 (KST)", country: "KR", title: "소매판매액지수 (전월 대비)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0601a", date: "2026-06-01", time: "09:00 (KST)", country: "KR", title: "수출 전년 대비", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0601b", date: "2026-06-01", time: "09:00 (KST)", country: "KR", title: "무역수지", importance: "3", source: "관세청", sourceUrl: "https://www.customs.go.kr" },
  { id: "kr-0605a", date: "2026-06-05", time: "08:00 (KST)", country: "KR", title: "소비자물가지수 CPI (전년 대비)", importance: "3", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0605b", date: "2026-06-05", time: "08:00 (KST)", country: "KR", title: "경상수지", importance: "2", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },
  { id: "kr-0617a", date: "2026-06-17", time: "08:00 (KST)", country: "KR", title: "실업률 (계절조정)", importance: "2", source: "통계청", sourceUrl: "https://kostat.go.kr" },
  { id: "kr-0619a", date: "2026-06-19", time: "08:00 (KST)", country: "KR", title: "생산자물가지수 PPI (전월 대비)", importance: "2", source: "한국은행", sourceUrl: "https://www.bok.or.kr" },

  // ═══════════════════ JP 2026년 1월 ═══════════════════
  { id: "jp-0109a", date: "2026-01-09", time: "08:30 (KST)", country: "JP", title: "가계지출 (전년 대비)", importance: "1", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0114a", date: "2026-01-14", time: "08:50 (KST)", country: "JP", title: "기업물가지수 CGPI (전년 대비)", importance: "2", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0121a", date: "2026-01-21", time: "12:00 (KST)", country: "JP", title: "일본은행(BOJ) 금리 결정", importance: "3", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0121b", date: "2026-01-21", time: "15:30 (KST)", country: "JP", title: "BOJ 총재 기자회견", importance: "3", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0124a", date: "2026-01-24", time: "08:30 (KST)", country: "JP", title: "전국 CPI (근원, 전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0127a", date: "2026-01-27", time: "08:30 (KST)", country: "JP", title: "도쿄 코어 CPI (전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0130a", date: "2026-01-30", time: "08:50 (KST)", country: "JP", title: "광공업생산지수 (속보, 전월 대비)", importance: "2", source: "경제산업성", sourceUrl: "https://www.meti.go.jp" },
  { id: "jp-0130b", date: "2026-01-30", time: "08:50 (KST)", country: "JP", title: "소매판매 (전년 대비)", importance: "2", source: "경제산업성", sourceUrl: "https://www.meti.go.jp" },
  { id: "jp-0130c", date: "2026-01-30", time: "08:30 (KST)", country: "JP", title: "실업률", importance: "2", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  // ═══════════════════ JP 2026년 2월 ═══════════════════
  { id: "jp-0203a", date: "2026-02-03", time: "08:30 (KST)", country: "JP", title: "실업률", importance: "2", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0212a", date: "2026-02-12", time: "08:50 (KST)", country: "JP", title: "기업물가지수 CGPI (전년 대비)", importance: "2", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0217a", date: "2026-02-17", time: "08:50 (KST)", country: "JP", title: "GDP 속보치 (Q4 2025, 전분기 대비)", importance: "3", source: "내각부", sourceUrl: "https://www.esri.cao.go.jp" },
  { id: "jp-0218a", date: "2026-02-18", time: "08:50 (KST)", country: "JP", title: "무역수지", importance: "2", source: "재무성", sourceUrl: "https://www.mof.go.jp" },
  { id: "jp-0220a", date: "2026-02-20", time: "08:30 (KST)", country: "JP", title: "전국 CPI (근원, 전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0220b", date: "2026-02-20", time: "08:50 (KST)", country: "JP", title: "기계주문 (전월 대비)", importance: "2", source: "내각부", sourceUrl: "https://www.esri.cao.go.jp" },
  { id: "jp-0227a", date: "2026-02-27", time: "08:30 (KST)", country: "JP", title: "도쿄 코어 CPI (전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0227b", date: "2026-02-27", time: "08:50 (KST)", country: "JP", title: "광공업생산지수 (속보, 전월 대비)", importance: "2", source: "경제산업성", sourceUrl: "https://www.meti.go.jp" },
  { id: "jp-0227c", date: "2026-02-27", time: "08:50 (KST)", country: "JP", title: "소매판매 (전년 대비)", importance: "2", source: "경제산업성", sourceUrl: "https://www.meti.go.jp" },
  // ═══════════════════ JP 2026년 3월 ═══════════════════
  { id: "jp-0303a", date: "2026-03-03", time: "08:30 (KST)", country: "JP", title: "실업률", importance: "2", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0303b", date: "2026-03-03", time: "08:30 (KST)", country: "JP", title: "가계지출 (전년 대비)", importance: "1", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0310a", date: "2026-03-10", time: "08:50 (KST)", country: "JP", title: "GDP 수정치 (Q4 2025, 전분기 대비)", importance: "3", source: "내각부", sourceUrl: "https://www.esri.cao.go.jp" },
  { id: "jp-0311a", date: "2026-03-11", time: "08:50 (KST)", country: "JP", title: "기업물가지수 CGPI (전년 대비)", importance: "2", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0313a", date: "2026-03-13", time: "12:00 (KST)", country: "JP", title: "일본은행(BOJ) 금리 결정", importance: "3", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0313b", date: "2026-03-13", time: "15:30 (KST)", country: "JP", title: "BOJ 총재 기자회견", importance: "3", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0318a", date: "2026-03-18", time: "08:50 (KST)", country: "JP", title: "무역수지", importance: "2", source: "재무성", sourceUrl: "https://www.mof.go.jp" },
  { id: "jp-0318b", date: "2026-03-18", time: "08:50 (KST)", country: "JP", title: "기계주문 (전월 대비)", importance: "2", source: "내각부", sourceUrl: "https://www.esri.cao.go.jp" },
  { id: "jp-0320a", date: "2026-03-20", time: "08:30 (KST)", country: "JP", title: "전국 CPI (근원, 전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0327a", date: "2026-03-27", time: "08:30 (KST)", country: "JP", title: "도쿄 코어 CPI (전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0331a", date: "2026-03-31", time: "08:50 (KST)", country: "JP", title: "일은 단칸 대기업 제조업 DI", importance: "3", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0331b", date: "2026-03-31", time: "08:50 (KST)", country: "JP", title: "광공업생산지수 (속보, 전월 대비)", importance: "2", source: "경제산업성", sourceUrl: "https://www.meti.go.jp" },
  { id: "jp-0331c", date: "2026-03-31", time: "08:50 (KST)", country: "JP", title: "소매판매 (전년 대비)", importance: "2", source: "경제산업성", sourceUrl: "https://www.meti.go.jp" },
  // ═══════════════════ JP 2026년 4~6월 ═══════════════════
  { id: "jp-0401a", date: "2026-04-01", time: "08:30 (KST)", country: "JP", title: "실업률", importance: "2", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0410a", date: "2026-04-10", time: "08:50 (KST)", country: "JP", title: "기업물가지수 CGPI (전년 대비)", importance: "2", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0415a", date: "2026-04-15", time: "08:50 (KST)", country: "JP", title: "무역수지", importance: "2", source: "재무성", sourceUrl: "https://www.mof.go.jp" },
  { id: "jp-0415b", date: "2026-04-15", time: "08:50 (KST)", country: "JP", title: "기계주문 (전월 대비)", importance: "2", source: "내각부", sourceUrl: "https://www.esri.cao.go.jp" },
  { id: "jp-0417a", date: "2026-04-17", time: "08:30 (KST)", country: "JP", title: "전국 CPI (근원, 전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0424a", date: "2026-04-24", time: "08:30 (KST)", country: "JP", title: "도쿄 코어 CPI (전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0427a", date: "2026-04-27", time: "12:00 (KST)", country: "JP", title: "일본은행(BOJ) 금리 결정", importance: "3", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0427b", date: "2026-04-27", time: "15:30 (KST)", country: "JP", title: "BOJ 총재 기자회견", importance: "3", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0430a", date: "2026-04-30", time: "08:50 (KST)", country: "JP", title: "광공업생산지수 (속보, 전월 대비)", importance: "2", source: "경제산업성", sourceUrl: "https://www.meti.go.jp" },
  { id: "jp-0430b", date: "2026-04-30", time: "08:50 (KST)", country: "JP", title: "소매판매 (전년 대비)", importance: "2", source: "경제산업성", sourceUrl: "https://www.meti.go.jp" },
  { id: "jp-0519a", date: "2026-05-19", time: "08:50 (KST)", country: "JP", title: "GDP 속보치 (Q1 2026, 전분기 대비)", importance: "3", source: "내각부", sourceUrl: "https://www.esri.cao.go.jp" },
  { id: "jp-0520a", date: "2026-05-20", time: "08:50 (KST)", country: "JP", title: "무역수지", importance: "2", source: "재무성", sourceUrl: "https://www.mof.go.jp" },
  { id: "jp-0522a", date: "2026-05-22", time: "08:30 (KST)", country: "JP", title: "전국 CPI (근원, 전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0529a", date: "2026-05-29", time: "08:30 (KST)", country: "JP", title: "도쿄 코어 CPI (전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0529b", date: "2026-05-29", time: "08:30 (KST)", country: "JP", title: "실업률", importance: "2", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0615a", date: "2026-06-15", time: "12:00 (KST)", country: "JP", title: "일본은행(BOJ) 금리 결정", importance: "3", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0615b", date: "2026-06-15", time: "15:30 (KST)", country: "JP", title: "BOJ 총재 기자회견", importance: "3", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0617a", date: "2026-06-17", time: "08:50 (KST)", country: "JP", title: "무역수지", importance: "2", source: "재무성", sourceUrl: "https://www.mof.go.jp" },
  { id: "jp-0619a", date: "2026-06-19", time: "08:30 (KST)", country: "JP", title: "전국 CPI (근원, 전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0626a", date: "2026-06-26", time: "08:30 (KST)", country: "JP", title: "도쿄 코어 CPI (전년 대비)", importance: "3", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },
  { id: "jp-0630a", date: "2026-06-30", time: "08:50 (KST)", country: "JP", title: "일은 단칸 대기업 제조업 DI", importance: "3", source: "일본은행 (BOJ)", sourceUrl: "https://www.boj.or.jp" },
  { id: "jp-0630b", date: "2026-06-30", time: "08:50 (KST)", country: "JP", title: "광공업생산지수 (속보, 전월 대비)", importance: "2", source: "경제산업성", sourceUrl: "https://www.meti.go.jp" },
  { id: "jp-0630c", date: "2026-06-30", time: "08:50 (KST)", country: "JP", title: "소매판매 (전년 대비)", importance: "2", source: "경제산업성", sourceUrl: "https://www.meti.go.jp" },
  { id: "jp-0630d", date: "2026-06-30", time: "08:30 (KST)", country: "JP", title: "실업률", importance: "2", source: "총무성 통계국", sourceUrl: "https://www.stat.go.jp" },

  // ═══════════════════ EU 2026년 1월 ═══════════════════
  { id: "eu-0107a", date: "2026-01-07", time: "19:00 (KST)", country: "EU", title: "유로존 CPI 속보 (전년 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0107b", date: "2026-01-07", time: "19:00 (KST)", country: "EU", title: "유로존 근원 CPI 속보", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0108a", date: "2026-01-08", time: "19:00 (KST)", country: "EU", title: "유로존 PPI (전월 대비)", importance: "2", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0108b", date: "2026-01-08", time: "19:00 (KST)", country: "EU", title: "유로존 소매판매 (전월 대비)", importance: "2", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0114a", date: "2026-01-14", time: "17:00 (KST)", country: "EU", title: "독일 CPI 최종 (전월 대비)", importance: "3", source: "Destatis", sourceUrl: "https://www.destatis.de" },
  { id: "eu-0114b", date: "2026-01-14", time: "19:00 (KST)", country: "EU", title: "독일 ZEW 경기기대지수", importance: "2", source: "ZEW", sourceUrl: "https://www.zew.de" },
  { id: "eu-0115a", date: "2026-01-15", time: "16:00 (KST)", country: "EU", title: "영국 CPI (전년 대비)", importance: "3", source: "ONS", sourceUrl: "https://www.ons.gov.uk" },
  { id: "eu-0117a", date: "2026-01-17", time: "19:00 (KST)", country: "EU", title: "유로존 CPI 최종 (전년 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0122a", date: "2026-01-22", time: "21:45 (KST)", country: "EU", title: "ECB 금리 결정", importance: "3", source: "ECB", sourceUrl: "https://www.ecb.europa.eu" },
  { id: "eu-0122b", date: "2026-01-22", time: "22:30 (KST)", country: "EU", title: "ECB 총재 기자회견", importance: "3", source: "ECB", sourceUrl: "https://www.ecb.europa.eu" },
  { id: "eu-0124a", date: "2026-01-24", time: "18:00 (KST)", country: "EU", title: "유로존 제조업·서비스 PMI 속보", importance: "3", source: "S&P Global", sourceUrl: "https://www.spglobal.com" },
  { id: "eu-0127a", date: "2026-01-27", time: "18:00 (KST)", country: "EU", title: "독일 IFO 기업환경지수", importance: "2", source: "IFO", sourceUrl: "https://www.ifo.de" },
  { id: "eu-0130a", date: "2026-01-30", time: "19:00 (KST)", country: "EU", title: "유로존 GDP 속보 (Q4 2025, 전분기 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0130b", date: "2026-01-30", time: "18:55 (KST)", country: "EU", title: "독일 실업률", importance: "2", source: "Bundesagentur", sourceUrl: "https://www.arbeitsagentur.de" },
  { id: "eu-0130c", date: "2026-01-30", time: "19:00 (KST)", country: "EU", title: "유로존 실업률", importance: "2", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  // ═══════════════════ EU 2026년 2월 ═══════════════════
  { id: "eu-0204a", date: "2026-02-04", time: "19:00 (KST)", country: "EU", title: "유로존 CPI 속보 (전년 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0204b", date: "2026-02-04", time: "19:00 (KST)", country: "EU", title: "유로존 근원 CPI 속보", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0205a", date: "2026-02-05", time: "19:00 (KST)", country: "EU", title: "유로존 PPI (전월 대비)", importance: "2", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0206a", date: "2026-02-06", time: "21:00 (KST)", country: "EU", title: "영국 중앙은행(BOE) 기준금리", importance: "3", source: "Bank of England", sourceUrl: "https://www.bankofengland.co.uk" },
  { id: "eu-0210a", date: "2026-02-10", time: "19:00 (KST)", country: "EU", title: "독일 ZEW 경기기대지수", importance: "2", source: "ZEW", sourceUrl: "https://www.zew.de" },
  { id: "eu-0213a", date: "2026-02-13", time: "16:00 (KST)", country: "EU", title: "영국 GDP (전분기 대비)", importance: "3", source: "ONS", sourceUrl: "https://www.ons.gov.uk" },
  { id: "eu-0213b", date: "2026-02-13", time: "16:00 (KST)", country: "EU", title: "영국 무역수지", importance: "1", source: "ONS", sourceUrl: "https://www.ons.gov.uk" },
  { id: "eu-0214a", date: "2026-02-14", time: "19:00 (KST)", country: "EU", title: "유로존 GDP 수정치 (Q4 2025)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0219a", date: "2026-02-19", time: "16:00 (KST)", country: "EU", title: "영국 CPI (전년 대비)", importance: "3", source: "ONS", sourceUrl: "https://www.ons.gov.uk" },
  { id: "eu-0220a", date: "2026-02-20", time: "18:00 (KST)", country: "EU", title: "유로존 제조업·서비스 PMI 속보", importance: "3", source: "S&P Global", sourceUrl: "https://www.spglobal.com" },
  { id: "eu-0224a", date: "2026-02-24", time: "18:00 (KST)", country: "EU", title: "독일 IFO 기업환경지수", importance: "2", source: "IFO", sourceUrl: "https://www.ifo.de" },
  { id: "eu-0227a", date: "2026-02-27", time: "18:55 (KST)", country: "EU", title: "독일 실업률", importance: "2", source: "Bundesagentur", sourceUrl: "https://www.arbeitsagentur.de" },
  // ═══════════════════ EU 2026년 3월 ═══════════════════
  { id: "eu-0303a", date: "2026-03-03", time: "19:00 (KST)", country: "EU", title: "유로존 CPI 속보 (전년 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0303b", date: "2026-03-03", time: "19:00 (KST)", country: "EU", title: "유로존 근원 CPI 속보", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0304a", date: "2026-03-04", time: "19:00 (KST)", country: "EU", title: "유로존 실업률", importance: "2", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0304b", date: "2026-03-04", time: "19:00 (KST)", country: "EU", title: "유로존 PPI (전월 대비)", importance: "2", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0306a", date: "2026-03-06", time: "19:00 (KST)", country: "EU", title: "유로존 GDP 최종 (Q4 2025, 전분기 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0306b", date: "2026-03-06", time: "19:00 (KST)", country: "EU", title: "유로존 소매판매 (전월 대비)", importance: "2", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0310a", date: "2026-03-10", time: "19:00 (KST)", country: "EU", title: "독일 ZEW 경기기대지수", importance: "2", source: "ZEW", sourceUrl: "https://www.zew.de" },
  { id: "eu-0311a", date: "2026-03-11", time: "16:00 (KST)", country: "EU", title: "독일 CPI (전월 대비)", importance: "3", source: "Destatis", sourceUrl: "https://www.destatis.de" },
  { id: "eu-0312a", date: "2026-03-12", time: "21:45 (KST)", country: "EU", title: "ECB 금리 결정", importance: "3", source: "ECB", sourceUrl: "https://www.ecb.europa.eu" },
  { id: "eu-0312b", date: "2026-03-12", time: "22:30 (KST)", country: "EU", title: "ECB 총재 기자회견", importance: "3", source: "ECB", sourceUrl: "https://www.ecb.europa.eu" },
  { id: "eu-0313a", date: "2026-03-13", time: "16:00 (KST)", country: "EU", title: "영국 GDP (전월 대비)", importance: "3", source: "ONS", sourceUrl: "https://www.ons.gov.uk" },
  { id: "eu-0318a", date: "2026-03-18", time: "19:00 (KST)", country: "EU", title: "유로존 CPI 최종 (전월 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0318b", date: "2026-03-18", time: "16:00 (KST)", country: "EU", title: "영국 CPI (전년 대비)", importance: "3", source: "ONS", sourceUrl: "https://www.ons.gov.uk" },
  { id: "eu-0319a", date: "2026-03-19", time: "21:00 (KST)", country: "EU", title: "영국 중앙은행(BOE) 기준금리", importance: "3", source: "Bank of England", sourceUrl: "https://www.bankofengland.co.uk" },
  { id: "eu-0324a", date: "2026-03-24", time: "18:00 (KST)", country: "EU", title: "유로존 제조업·서비스 PMI 속보", importance: "3", source: "S&P Global", sourceUrl: "https://www.spglobal.com" },
  { id: "eu-0325a", date: "2026-03-25", time: "18:00 (KST)", country: "EU", title: "독일 IFO 기업환경지수", importance: "2", source: "IFO", sourceUrl: "https://www.ifo.de" },
  { id: "eu-0331a", date: "2026-03-31", time: "18:55 (KST)", country: "EU", title: "독일 실업률", importance: "2", source: "Bundesagentur", sourceUrl: "https://www.arbeitsagentur.de" },
  // ═══════════════════ EU 2026년 4~6월 ═══════════════════
  { id: "eu-0401a", date: "2026-04-01", time: "19:00 (KST)", country: "EU", title: "유로존 CPI 속보 (전년 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0401b", date: "2026-04-01", time: "19:00 (KST)", country: "EU", title: "유로존 실업률", importance: "2", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0407a", date: "2026-04-07", time: "19:00 (KST)", country: "EU", title: "유로존 소매판매 (전월 대비)", importance: "2", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0407b", date: "2026-04-07", time: "19:00 (KST)", country: "EU", title: "독일 ZEW 경기기대지수", importance: "2", source: "ZEW", sourceUrl: "https://www.zew.de" },
  { id: "eu-0415a", date: "2026-04-15", time: "16:00 (KST)", country: "EU", title: "영국 CPI (전년 대비)", importance: "3", source: "ONS", sourceUrl: "https://www.ons.gov.uk" },
  { id: "eu-0416a", date: "2026-04-16", time: "21:45 (KST)", country: "EU", title: "ECB 금리 결정", importance: "3", source: "ECB", sourceUrl: "https://www.ecb.europa.eu" },
  { id: "eu-0416b", date: "2026-04-16", time: "22:30 (KST)", country: "EU", title: "ECB 총재 기자회견", importance: "3", source: "ECB", sourceUrl: "https://www.ecb.europa.eu" },
  { id: "eu-0423a", date: "2026-04-23", time: "18:00 (KST)", country: "EU", title: "유로존 제조업·서비스 PMI 속보", importance: "3", source: "S&P Global", sourceUrl: "https://www.spglobal.com" },
  { id: "eu-0427a", date: "2026-04-27", time: "18:00 (KST)", country: "EU", title: "독일 IFO 기업환경지수", importance: "2", source: "IFO", sourceUrl: "https://www.ifo.de" },
  { id: "eu-0430a", date: "2026-04-30", time: "19:00 (KST)", country: "EU", title: "유로존 GDP 속보 (Q1 2026, 전분기 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0430b", date: "2026-04-30", time: "18:55 (KST)", country: "EU", title: "독일 실업률", importance: "2", source: "Bundesagentur", sourceUrl: "https://www.arbeitsagentur.de" },
  { id: "eu-0507a", date: "2026-05-07", time: "21:00 (KST)", country: "EU", title: "영국 중앙은행(BOE) 기준금리", importance: "3", source: "Bank of England", sourceUrl: "https://www.bankofengland.co.uk" },
  { id: "eu-0512a", date: "2026-05-12", time: "19:00 (KST)", country: "EU", title: "독일 ZEW 경기기대지수", importance: "2", source: "ZEW", sourceUrl: "https://www.zew.de" },
  { id: "eu-0519a", date: "2026-05-19", time: "19:00 (KST)", country: "EU", title: "유로존 CPI 최종 (전월 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0520a", date: "2026-05-20", time: "16:00 (KST)", country: "EU", title: "영국 CPI (전년 대비)", importance: "3", source: "ONS", sourceUrl: "https://www.ons.gov.uk" },
  { id: "eu-0522a", date: "2026-05-22", time: "18:00 (KST)", country: "EU", title: "유로존 제조업·서비스 PMI 속보", importance: "3", source: "S&P Global", sourceUrl: "https://www.spglobal.com" },
  { id: "eu-0525a", date: "2026-05-25", time: "18:00 (KST)", country: "EU", title: "독일 IFO 기업환경지수", importance: "2", source: "IFO", sourceUrl: "https://www.ifo.de" },
  { id: "eu-0602a", date: "2026-06-02", time: "19:00 (KST)", country: "EU", title: "유로존 CPI 속보 (전년 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0602b", date: "2026-06-02", time: "19:00 (KST)", country: "EU", title: "유로존 실업률", importance: "2", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0604a", date: "2026-06-04", time: "21:45 (KST)", country: "EU", title: "ECB 금리 결정", importance: "3", source: "ECB", sourceUrl: "https://www.ecb.europa.eu" },
  { id: "eu-0604b", date: "2026-06-04", time: "22:30 (KST)", country: "EU", title: "ECB 총재 기자회견", importance: "3", source: "ECB", sourceUrl: "https://www.ecb.europa.eu" },
  { id: "eu-0609a", date: "2026-06-09", time: "19:00 (KST)", country: "EU", title: "독일 ZEW 경기기대지수", importance: "2", source: "ZEW", sourceUrl: "https://www.zew.de" },
  { id: "eu-0613a", date: "2026-06-13", time: "16:00 (KST)", country: "EU", title: "영국 GDP (전월 대비)", importance: "3", source: "ONS", sourceUrl: "https://www.ons.gov.uk" },
  { id: "eu-0617a", date: "2026-06-17", time: "16:00 (KST)", country: "EU", title: "영국 CPI (전년 대비)", importance: "3", source: "ONS", sourceUrl: "https://www.ons.gov.uk" },
  { id: "eu-0618a", date: "2026-06-18", time: "21:00 (KST)", country: "EU", title: "영국 중앙은행(BOE) 기준금리", importance: "3", source: "Bank of England", sourceUrl: "https://www.bankofengland.co.uk" },
  { id: "eu-0618b", date: "2026-06-18", time: "19:00 (KST)", country: "EU", title: "유로존 CPI 최종 (전년 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0623a", date: "2026-06-23", time: "18:00 (KST)", country: "EU", title: "유로존 제조업·서비스 PMI 속보", importance: "3", source: "S&P Global", sourceUrl: "https://www.spglobal.com" },
  { id: "eu-0623b", date: "2026-06-23", time: "18:00 (KST)", country: "EU", title: "독일 IFO 기업환경지수", importance: "2", source: "IFO", sourceUrl: "https://www.ifo.de" },
  { id: "eu-0630a", date: "2026-06-30", time: "19:00 (KST)", country: "EU", title: "유로존 GDP 최종 (Q1 2026, 전분기 대비)", importance: "3", source: "Eurostat", sourceUrl: "https://ec.europa.eu/eurostat" },
  { id: "eu-0630b", date: "2026-06-30", time: "18:55 (KST)", country: "EU", title: "독일 실업률", importance: "2", source: "Bundesagentur", sourceUrl: "https://www.arbeitsagentur.de" },
];

export async function GET(request: NextRequest) {
  const country = request.nextUrl.searchParams.get("country");
  const filtered = country ? EVENTS.filter((e) => e.country === country) : EVENTS;
  return NextResponse.json(filtered);
}
